### ISSUE TITLE
Вёрстка - Главная - Верхнее меню

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#1]
У меню и пунктов меню должны быть обводки #009646 2px

**Comment by xeniia-merkusheva** [comment]
Стили hover и active одинаковые - желтый фон и темные буквы

**Comment by fiction13** [comment]
- [x] обводки у пунктов меню
- [x] стили ховер и актив

**Comment by xeniia-merkusheva** [comment]
По ховеру желтые обводки отстутствуют с правой стороны

**Comment by fiction13** [comment]
В макете нет желтых обводок с правой стороны.

Делать?

**Comment by xeniia-merkusheva** [comment]
И правда, нет. Извиняюсь. Да, делать

**Comment by fiction13** [comment]
Сделал
