### ISSUE TITLE
Главная - Адаптив - Верхнее меню

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#10]
1) Всё меню зеленым #63c889 с разделителями цвета обводки темно-зеленой
2) кнопка бутерброда - нужны бордеры темно-желтые
3) Текст не капсом, обычный как в десктопной версии

**Comment by fiction13** [comment]
1. Можно дать пояснения? Я не понял, какие части зеленым, где должна быть обводка?
2. Где именно на бутерброде нужны темно-желтые (это какие?) бордеры?
3. Сделал текст обычным.

**Comment by xeniia-merkusheva** [comment]
![image](https://cloud.githubusercontent.com/assets/25584619/22729118/658833ac-edf2-11e6-99d3-6fe597941a9b.png)

**Comment by xeniia-merkusheva** [comment]
Только цвет иконки бутерброда #363535

**Comment by fiction13** [comment]
Сделал
