### ISSUE TITLE
Главная - Адаптив - Поднять форму

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#12]
![screenshot-tundramedia github io 2017-02-10 13-52-47](https://cloud.githubusercontent.com/assets/25584619/22824383/c0aa50e2-ef98-11e6-95a7-1d4ef53fc6f6.png)
Надо поднять форму, а надпись на мобильных про легкую аренду скрывать.

**Comment by fiction13** [comment]
Форму поднял, слоган на мобильных скрыл.
