### ISSUE TITLE
2й шаг бронирования — Карточка машины

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#15]
В цене каждые три знака разделяются пробелом 10 000

**Comment by xeniia-merkusheva** [comment]
А еще нужно паддинги проверить, сейчас карточка растянута по вертикали, а по горизонтали нужны большие отступы от краев

**Comment by fiction13** [comment]
Моя ошибка, поправил паддинги. Цены поправил.
