### ISSUE TITLE
Главная - Форма поиска

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#2]
1) По высоте зеленая и белая части выше, чем в дизайне
2) Заголовки полей и содержимое должны быть Medium жирности
3) Иконки календаря и у желтой кнопки
4) Логика взаимодействия с формой: при клике на первое поле сразу открывается выпадашка со станциями, после выбора станции сразу открывается выбор даты и времени. После выбора даты фокус на втором поле и открывается выпадашка станции - затем даты и время

**Comment by xeniia-merkusheva** [comment]
А можно сделать, чтобы по клику не только на текст в поле, но и вообще по белому полю открывались выпадашки? И курсор - рука

**Comment by fiction13** [comment]
С формой поиска не все так просто. 

1. Поясни пожалуйста, что значит зеленая и белая части выше, чем в дизайне? Я брал размеры из psd.
2. Сделал. Но гитхаб почему-то не подгружает шрифты.
3. Иконки поставил.
4. Порядок открытия/закрытия критичен? Я могу доработать ее в этом направлении, но это займет некоторое время.

**Comment by fiction13** [comment]
Так как диапазон выбора времени на форме очень большой, то получалась большая портянка. Я ограничил высоту выбора времени 200px и поставил туда perfect scrollbar, стилизовал немного, посмотри, устроит ли так?

**Comment by xeniia-merkusheva** [comment]
1. Наверное так казалось из-за шрифтов, сейчас ок.
4. Открыте-закрытие автоматически очень важно
5. Сейчас открывается выпадашка только по клику на текст
6. Диапазон времени можно по высоте как календарь сделать
7. Возможно ли время отображать как на дизайне? Месяц словом, в одну строку?

**Comment by fiction13** [comment]
1. Шрифты настроил, подгрузились.
2. Сделал автматическое открытие по шагам.
3. Сделал выпадание по клику на все поле (кроме календаря).
4-5. С диапазоном сложновато. Весь текст не помещается, поэтому я сделал такое отображение времени, как оно есть. Если делать месяц словом - то даже в таком случае не вмещается. Если что, то форматировать дату я могу как угодно.

**Comment by xeniia-merkusheva** [comment]
5 - нужно сделать словами, если что, шрифт уменьшить

**Comment by fiction13** [comment]
Никак не получается вписать текстовый месяц. Он занимает слишком много места даже при меньшем шрифте. Может стоит отказаться от текстового месяца или изменить дизайн?

**Comment by fiction13** [comment]
Сделал текстовый месяц и год из 4 цифр.
