### ISSUE TITLE
3й шаг бронирования — Доп. услуги

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#20]
При отмечании чекбокса, появляется какая-то желтая обводка вокруг него
![image](https://cloud.githubusercontent.com/assets/25584619/22877159/1ee5b392-f1e5-11e6-8f5d-806852ab2c2c.png)

**Comment by fiction13** [comment]
Убрал обводку.

**Comment by xeniia-merkusheva** [comment]
![image](https://cloud.githubusercontent.com/assets/25584619/23038022/8ac16078-f499-11e6-8061-1951e5b8a5d2.png)
иконки в блоке сверху надо выровнять, сейчас кондиционер как будто вверх улетел

**Comment by xeniia-merkusheva** [comment]
А еще рубль на другую строчку перенесся

**Comment by fiction13** [comment]
Поправил
