### ISSUE TITLE
2й шаг бронирования - "Открыть карту" под полями станций и дат

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#22]

**Comment by fiction13** [comment]
В дизайне кстати кнопки нет.

Поставил.

**Comment by xeniia-merkusheva** [comment]
![easy-rent-2step](https://cloud.githubusercontent.com/assets/25584619/23057270/5cf24790-f500-11e6-8804-2230dfbd38cb.png)
Вот на этом шаге

**Comment by fiction13** [comment]
Сделал
