### ISSUE TITLE
Главная - Слайдер с машинами

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#3]
1) Уменьшить расстояние от цены до названия авто
2) На кнопке справа должно помещаться "в парк" в одну строчку
3) Иконки рубля - я использовала символ рубля из шрифта arial

**Comment by fiction13** [comment]
1. Уменьшил растояние.
2. Сделал в 1 строку.
3. Поставил иконку рубля.

**Comment by xeniia-merkusheva** [comment]
3. У меня иконка рубля выглядит как буква О

**Comment by fiction13** [comment]
3. Шрифты прогрузились - рубль образовался. В html довольно проблематично использовать такие вещт, не прибегая к сторонним шрифтам, я вот подгрузил этот - https://www.artlebedev.ru/kovodstvo/sections/159/

**Comment by xeniia-merkusheva** [comment]
Arial же стандартный шрифт. И в нем есть иконка рубля

**Comment by fiction13** [comment]
Ага, Arial стандартный шрифт. И поддержку символа рубля в нем добавили если не ошибаюсь с Windows 8. А значит все, кто сидит на windows XP, а таких людей много, увидят пустой прямоугольник. Если этот вариант устроит, я пропишу символ рубля, нет проблем.

В итоге самый надежный способ отображения символа рубля - подгрузка стиля с единственным символом, использование иконок типа fontawesome или обычное изображение.
