### ISSUE TITLE
Главная - Отзывы

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#7]
1) На кнопках подписи с маленькой буквы
2) На кнопке по наведению пропадает иконка

**Comment by fiction13** [comment]
1. Написал с маленькой буквы.
2. Вернул иконки при наведении.

**Comment by xeniia-merkusheva** [comment]
3. Еще просьба отображение даты тоже сделать с месяцем словами (4 июня 2016, например)

**Comment by fiction13** [comment]
3. Сделал.
