### ISSUE TITLE
Главная - Футер

### ISSUE THREAD

**Issue by xeniia-merkusheva** [Tundramedia/okrent#9]
1) Добавить отступ в самом низу футера, больше верхнего 
.fl-page-wrapper #footer {
    padding: 20px 0 45px;

**Comment by xeniia-merkusheva** [comment]
2) Кнопка "Арендовать авто" - текст нежирный, стрелочка слева.
3) Иконки соцсетей вместе с улыбочкой при наведении должны становиться желтыми, то же для active
4) Пункты меню при наведении желтые     color: #ffd814;

**Comment by fiction13** [comment]
1. Добавил отступ.
2. Убрал жирный текст, добавил стрелочку.
**3. Нужны желтые иконки соц сетей.**
4. Поправил стиль при наведении.

**Comment by xeniia-merkusheva** [comment]
А я думала, что они css-ом перекрашиваться будут. Так нельзя?

**Comment by xeniia-merkusheva** [comment]
[иконки.zip](https://github.com/Tundramedia/okrent/files/760086/default.zip)

**Comment by fiction13** [comment]
В CSS есть фильтры, которые можно наложить на изображение, например, при ховере. Но они нам тут никак не помогут.

Иконки принял, ок.

**Comment by fiction13** [comment]
Поменял иконки.
